### ISSUE TITLE
Registering for deprecated event 'currentDocumentChange'

### ISSUE THREAD

**Issue by DH3ALEJANDRO** [cmgddd/Brackets-css-color-preview#6]
Hi,

as of (at least) Brackets 1.1. the `DocumentManager.currentDocumentChange` has been deprecated in favor of `MainViewManager.currentFileChange` which is why Brackets throws Registering for deprecated event `currentDocumentChange`. Instead, use `MainViewManager.currentFileChange`.
for this block:
```
$(DocumentManager).on("currentDocumentChange", CssColorPreview.onChanged);
$(DocumentManager).off("currentDocumentChange", CssColorPreview.onChanged);
```
only change
```
$(DocumentManager).on("currentFileChange", CssColorPreview.onChanged);
$(DocumentManager).off("currentFileChange", CssColorPreview.onChanged);
```

**Comment by cmgddd** [comment]
@DH3ALEJANDRO thanks,updated. But I didn't knew  the event of currentDocumentChange is not worked.  And I just used the `EditorManager.activeEditorChange`(which covers all editors, not just full-sized editors) instead.

**Comment by alessandrio** [comment]
ok thanks (is the most effective way that may exist, "activeEditorChange"), good life for you :)
