### ISSUE TITLE
Possible CSS Preprocessor support?

### ISSUE THREAD

**Issue by whaaaley** [cmgddd/Brackets-css-color-preview#7]
![image](http://cl.ly/image/3f40411Z2105/Screen%20Shot%202015-01-19%20at%2012.19.19%20AM.png)

When using color names in Sass or Less variables the colors in the sidebar aren't reflective of the colors stored in the variables, just the descriptive names inside the variables. It would be really awesome if it could be reflective of the colors inside the variables, or disabled for variable names, because sometimes it gets a little confusing.

**Comment by cmgddd** [comment]
@dustindowell22 Yea,it sounds a great idea. I think that would be  possible to implent in single file. But I don't know how to get these variables of color across the less/sass files. Do you have any ideas?

**Comment by whaaaley** [comment]
Ah, yeah, that's a problem.

It looks like all the working files are wrapped in this class `.pane-content` and each pane has it's own div. The focused pane has a class `.CodeMirror-focused'.

All other files don't get loaded until they're loaded until they're clicked on. I wonder if there's a way to temporarily load all SCSS and LESS in a current project, search for variables containing colors and cache them, then when each file loads you'll have all of the color variables at hand.

It wouldn't work for more complex color variables that require compilation, though, unless there's a way to integrate with one of the Sass/Less compiler extensions, or, write out some minimal color preprocessing by hand.
